### ISSUE TITLE
make it compatible with all mac os versions

### ISSUE THREAD

**Issue by emad2333** [ethandgoodhart/IPAEdit#1]
Its only compatible with mac os big sur , make it compatible all mac os versions

**Comment by ethandgoodhart** [comment]
It should be compatible with macOS 10.11 and above now so that would include Yosemite, El Capitan, Sierra, High Sierra, Mojave, and Big Sur.

**Comment by emad2333** [comment]
But it snot compatible with MacOS Catalina 10.15.4
